### ISSUE TITLE
YEAR_IN_MINUTES is actually the value of the number of seconds in year

### ISSUE THREAD

**Issue by mofojed** [realityforge/gwt-cache-filter#6]
This variable should be named `YEAR_IN_SECONDS`:
https://github.com/realityforge/gwt-cache-filter/blob/5a1732278280aeda55a042ef76ba78a8008d19ab/src/main/java/org/realityforge/gwt/cache_filter/GWTCacheControlFilter.java#L21

**Comment by realityforge** [comment]
Thanks - fixed up!
